### ISSUE TITLE
macOS - where's the dmg?

### ISSUE THREAD

**Issue by markhdavid** [AlizaMedicalImaging/AlizaMS#10]
Readme gives instructions for macOS saying only to "open the DMG file". What DMG file? Is there a separate download file? If so, shouldn't that be in the included in these instructions?

**Comment by issakomi** [comment]
Hello,
s. Releases, latest, there is AlizaMS-1.7.4.dmg
https://github.com/AlizaMedicalImaging/AlizaMS/releases/tag/v1.7.4

**Comment by issakomi** [comment]
Thank you, I have added the link to Readme.
