### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by ivabus** [AlizaMedicalImaging/AlizaMS#13]
It would be nice, if in AlizaMS would have support for saving studies in database, like it done in OsiriX. It is very useful. Like on screenshot.
![Screenshot](https://www.osirix-viewer.com/wp2015/wp-content/uploads/2015/09/Database-1024x576.png)

**Comment by ivabus** [comment]
In OsiriX you can copy any DICOM data in it's local database.

**Comment by issakomi** [comment]
Thank you. Yes, you are right. I hope to make it. Currently, as a workaround, it is possible to use CTK database, it is **temporary** solution. There is standalone CTK build for Windows https://github.com/AlizaMedicalImaging/CTK/releases or it may work with Slicer's CTK database too.
