### ISSUE TITLE
1.8.3 version

### ISSUE THREAD

**Issue by alcir** [AlizaMedicalImaging/AlizaMS#14]
Hello @issakomi how are you?
Just a question: out of curiosity when do you think 1.8.0 will be released?
Thanks.

**Comment by issakomi** [comment]
Hello Alessio, how are you?
I hope the next release will be done very soon, maybe next week. I shall update the issue.
Thank you!

**Comment by issakomi** [comment]
I have just done 1.8.0

No changes are required for Flatpak distribution.

For package, s. below changes in spec file:

```
...
BuildRequires:  lcms2-devel
...
...
rm -fr alizalcms/
rm -rf debian-12-qt5/
rm -rf debian-12-qt6/
...
...
  -DALIZA_USE_SYSTEM_LCMS2:BOOL=ON \
...
```

It is LCMS2, a library to support ICC color profiles, it is always available on Linux, one of Gimp dependencies, i have checked. Like with other dependencies -- both internal version or system's can be used.

Thank you very much!

**Comment by issakomi** [comment]
Found a typo in metainfo, the post above post is applicable, changes the version to **1.8.1**

**Comment by alcir** [comment]
If I set `-DALIZA_USE_SYSTEM_LCMS2:BOOL=ON` for cmake, the
```
#ifdef USE_SYSTEM_LCMS2
#include "lcms2.h"
```
part in [`dicom/dicomutils.cpp`](https://github.com/AlizaMedicalImaging/AlizaMS/blob/5ecfb9c9bace5508357be8e864760e67a227a96a/dicom/dicomutils.cpp#L86) is not taken into account. 

```
/blah/AlizaMS-1.8.1/dicom/dicomutils.cpp:89:10: fatal error: alizalcms/lcms2.h: No such file or directory
   89 | #include "alizalcms/lcms2.h"
      |          ^~~~~~~~~~~~~~~~~~~
```

You know I'm not well versed with development, but if I add `add_compile_definitions(USE_SYSTEM_LCMS2)` after https://github.com/AlizaMedicalImaging/AlizaMS/blob/5ecfb9c9bace5508357be8e864760e67a227a96a/CMakeLists.txt#L776
then it works.

**Comment by issakomi** [comment]
OMG, i shall look at it now

**Comment by issakomi** [comment]
There is old version
`#ifdef USE_SYSTEM_LCMS2`
instead of 
`#ifdef ALIZA_USE_SYSTEM_LCMS2`
I shall fix it now

**Comment by alcir** [comment]
> There is old version `#ifdef USE_SYSTEM_LCMS2` instead of `#ifdef ALIZA_USE_SYSTEM_LCMS2` I shall fix it now

Mmm, I'm not sure, but also with ` #ifdef ALIZA_USE_SYSTEM_LCMS2`, that if statement is not taken into account.

**Comment by issakomi** [comment]
i have fixed, will take several minutes to test locally

**Comment by alcir** [comment]
Oh ok `add_definitions(-DALIZA_USE_SYSTEM_LCMS2)` + ` #ifdef ALIZA_USE_SYSTEM_LCMS2`
Works here :+1:

**Comment by issakomi** [comment]
Done release 1.8.3, i hope _Flatpak_ will not be angry for frequent updates, Flatpak build was not affected by the bug, but i have updated.

**Comment by alcir** [comment]
Great @issakomi 
Thank you

**Comment by issakomi** [comment]
Thank you for the bug-fix, it is important.
