### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [AlizaMedicalImaging/AlizaMS#17]
I would like to point out that identifiers like “[`DICOMUTILS__H_`](https://github.com/AlizaMedicalImaging/AlizaMS/blob/45c07b5831b7d88a43629e1a380c18c6b4c9186f/dicom/dicomutils.h#L1 "Update candidate")” and “[`SQTREE__H__`](https://github.com/AlizaMedicalImaging/AlizaMS/blob/926d1c0b38961b0c393dd19301eb3497cdcb2aab/browser/sqtree.h#L1 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by issakomi** [comment]
Thanks! I renamed all definitions to standard compliant.
