### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [AlizaMedicalImaging/AlizaMS#18]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CAPICryptographicMessageSyntax::ParseCertificateFile](https://github.com/AlizaMedicalImaging/AlizaMS/blob/4f2090972bb62de9ae88bbdca9edb276f85dd631/mdcm/Source/Common/mdcmCAPICryptographicMessageSyntax.cxx#L96 "CAPICryptographicMessageSyntax::ParseCertificateFile function")
- [Observer](https://github.com/AlizaMedicalImaging/AlizaMS/blob/e9eb991033128c2c4d77283e976c06c53dc374a8/mdcm/Source/Common/mdcmSubject.cxx#L39 "Destructor for Observer")
- [Preamble](https://github.com/AlizaMedicalImaging/AlizaMS/blob/8fe742707fa4f452542ea4f3953df3279848a486/mdcm/Source/DataStructureAndEncodingDefinition/mdcmPreamble.cxx#L35 "Destructor for Preamble")

**Comment by elfring** [comment]
[More update candidates were left over](https://github.com/AlizaMedicalImaging/AlizaMS/blob/cb5784079f37269c553c167cc3a8ce455d3c0d4e/mdcm/Source/DataStructureAndEncodingDefinition/mdcmPreamble.cxx#L53 "Reconsidering some null pointer checks").

:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by issakomi** [comment]
> More update candidates were left over.


```cpp
  if (Internal)
  {
    delete[] Internal;
    Internal = NULL;
  }
```

I think here it is OK, IMHO. There is also the assignment step `Internal = NULL;` (to make the function re-entrant).

**Comment by elfring** [comment]
Such null pointer checks are also redundant.

:thought_balloon: [They can be replaced by the usage of smart pointers](https://github.com/AlizaMedicalImaging/AlizaMS/issues/19 "Using smart pointers"), can't they?
