### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [AlizaMedicalImaging/AlizaMS#19]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [CAPICryptographicMessageSyntax::ParseCertificateFile](https://github.com/AlizaMedicalImaging/AlizaMS/blob/cb5784079f37269c553c167cc3a8ce455d3c0d4e/mdcm/Source/Common/mdcmCAPICryptographicMessageSyntax.cxx#L66)
- [ImageSlice](https://github.com/AlizaMedicalImaging/AlizaMS/blob/aa0f6c9b18bc7bafa7aa4ff97233ccc4e0321d26/common/structures.h#L328)
- [qMeshData](https://github.com/AlizaMedicalImaging/AlizaMS/blob/90c71822fe1abfd75932868673e095dd8e467d31/CG/glwidget.cpp#L93)

**Comment by issakomi** [comment]
Thank you. I am sure it is good approach to use _std::unique_ptr_. But the candidates above are difficult. 1st is the file from MDCM, this particular file is unused in AlizaMS and it will require a lot of work to change the whole MDCM library. It was written before C++11. Maybe later. Other files are from CG part, it is very stable part, under the hood of _std::unique_ptr_ is the same new/delete, it is easier to workaround exceptions and error conditions, but current logic imply this already. Also maybe later.
I will surely consider _std::unique_ptr_ in a new code.
Thank you again!

**Comment by elfring** [comment]
:thinking: How do you think about to keep this issue open until [inappropriate implementation details](https://github.com/AlizaMedicalImaging/AlizaMS/blob/cb5784079f37269c553c167cc3a8ce455d3c0d4e/mdcm/Source/Common/mdcmCAPICryptographicMessageSyntax.cxx#L66 "Update candidate: [CAPICryptographicMessageSyntax::ParseCertificateFile](https://github.com/AlizaMedicalImaging/AlizaMS/blob/cb5784079f37269c553c167cc3a8ce455d3c0d4e/mdcm/Source/Common/mdcmCAPICryptographicMessageSyntax.cxx#L66)") will finally be fixed?
