### ISSUE TITLE
1.8.3 sha256sum

### ISSUE THREAD

**Issue by alcir** [AlizaMedicalImaging/AlizaMS#21]
Hello @issakomi 
Have you seen? https://buildbot.flathub.org/#/builders/35/builds/2482
What happened? What do you think? Why the sha256sum of the tar.gz changed compared with the checksum that was calculated the last time the package was built?

**Comment by issakomi** [comment]
Hello,
I didn't change anything. I shall look closer.

**Comment by issakomi** [comment]
I don't have an explanation. The "Source code" links (_.zip_ and _.tar.gz_) are generated by Github at release, I can not change them by editing.
I have checked out "-b v1.8.3" and compared with downloaded and extracted _.tar.gz_ (it has in fact sha256 3746e1cdee9891570dd22a602f3022a6203fc90abc0b0ad91a543a55b4bd9f03). All files are identical. No idea.

**Comment by issakomi** [comment]
S. https://github.com/orgs/community/discussions/45830

**Comment by alcir** [comment]
Ok

**Comment by issakomi** [comment]
Thank you. It seems the problem has been fixed. Old sha256 again.
