### ISSUE TITLE
QT6 and Fedora

### ISSUE THREAD

**Issue by alcir** [AlizaMedicalImaging/AlizaMS#27]
Sorry @issakomi I need your advice.
If I use `-DALIZA_QT_VERSION:STRING=6`
I get
```
CMake Error at /usr/lib64/cmake/Qt6Core/Qt6CoreVersionlessTargets.cmake:42 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: Qt::Core

  Targets not yet defined: Qt::CorePrivate

Call Stack (most recent call first):
  /usr/lib64/cmake/Qt6Core/Qt6CoreConfig.cmake:65 (include)
  /usr/lib64/cmake/Qt6/Qt6Config.cmake:167 (find_package)
  CMakeLists.txt:588 (find_package)


-- Configuring incomplete, errors occurred!
```

I don't know. I installed `qt6-qtbase-private-devel` package.

And, for the records, if I also install `qt5-qtbase-private-devel` I get

```
CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "alizams".
```

**Comment by issakomi** [comment]
I am not yet sure. I build with Qt's binary Qt6 release on Debian and masOS without such issues. I shall take a closer look today. Thank you!

**Comment by issakomi** [comment]
For Qt5 on Linux I always use distribution's packages. Probably if multiple Qt versions are installed the PATH should point to Qt's bin folder there _qmake_ is. Not yet sure, didn't run into the issues.

**Comment by issakomi** [comment]
I have tested with Fedora 39.

Manual build (download or clone and build ITK and then build AlizaMS manually) works with Qt6 without problems (required Qt6 packages: `qt6-qtbase-devel, qt6-qtsvg-devel, qt6-qt5compat-devel`).

Trying to build the package I run into exactly the same issue as you have described above (qmake was correct, from Qt6). I thing the problem is this really huge amount of `InsightToolkit-devel` dependencies, 188 packages, among them is `InsightToolkit-vtk-devel-4.13.3-14`, the last one depends on VTK, VTK depends on Qt5 development packages, they interfere somehow in CMake with Qt6 (Qt6 is based on cmake).

It is better to stay with Qt5. And probably I shall also revert the recommendation about OpenGL profile (even if works well in Fedora 39). AlizaMS package works good, better not to change anything IMHO.

ITK package is very old, 4.13, and probably it will take long time till someone package newer version, it is over-complicated task.

```
Installed:
  InsightToolkit-devel-4.13.3-14.fc39.x86_64                                    
  InsightToolkit-vtk-4.13.3-14.fc39.x86_64                                      
  InsightToolkit-vtk-devel-4.13.3-14.fc39.x86_64
  ...
  ...
  ...
  qt5-designer-5.15.9-1.fc39.x86_64                                             
  qt5-doctools-5.15.9-1.fc39.x86_64                                             
  qt5-linguist-5.15.9-1.fc39.x86_64                                             
  qt5-qtbase-devel-5.15.9-3.fc39.x86_64                                         
  qt5-qtdeclarative-devel-5.15.9-1.fc39.x86_64                                  
  qt5-qtlocation-5.15.9-1.fc39.x86_64                                           
  qt5-qtsensors-5.15.9-1.fc39.x86_64                                            
  qt5-qttools-5.15.9-1.fc39.x86_64                                              
  qt5-qttools-common-5.15.9-1.fc39.noarch                                       
  qt5-qttools-devel-5.15.9-1.fc39.x86_64                                        
  qt5-qttools-libs-designer-5.15.9-1.fc39.x86_64                                
  qt5-qttools-libs-designercomponents-5.15.9-1.fc39.x86_64                      
  qt5-qttools-libs-help-5.15.9-1.fc39.x86_64                                    
  qt5-qtwebchannel-5.15.9-1.fc39.x86_64                                         
  qt5-qtwebkit-5.212.0-0.75alpha4.fc39.x86_64                                   
  qt5-qtwebkit-devel-5.212.0-0.75alpha4.fc39.x86_64                             
  qt5-qtx11extras-devel-5.15.9-1.fc39.x86_64                                    
  qt5-rpm-macros-5.15.9-1.fc39.noarch
  ...
  ...
  ...
```

Sorry, I am afraid I can not help with the issue.

**Comment by issakomi** [comment]
Good news is that I finally found the [workaround](https://github.com/AlizaMedicalImaging/AlizaMS/commit/fbaac69bf60c79f6b4dc302dac4792489fa6e15a) to fix mysterious transparency problem with Wayland. No need to force `xcb` platform, Wayland works now too on Fedora 39 + Qt6. Tested with OpenGL Core Profile. Probably Core Profile is the way to go. I tested everywhere, seems to work, there is new fallback to start application without OpenGL if something goes wrong (unlikely). I shall test Fedora 38 + Qt5, I remember Qt5 worked very bad with Wayland.

**Comment by issakomi** [comment]
I close the topic. Unfortunately, there is nothing I can do on my end. Probably the next Flathub release will be with Qt6. If you have an idea for a workaround for the rpm package, please reopen. Thank you!

**Comment by issakomi** [comment]
@alcir 

> OpenGL Core Profile is the default now. Nothing special has to be done for configuration.

I have seen new [package](https://src.fedoraproject.org/rpms/alizams/c/ade4cae6e39fdc56e9310fecf68a815ba926d84f?branch=rawhide).  Thank you very much! Just a minor comment, the option `-DALIZA_QT5_COREGL:BOOL=ON` doesn't exist. It is `ALIZA_COREGL` [now](https://github.com/AlizaMedicalImaging/AlizaMS/blob/master/CMakeLists.txt#L91-L94) (applicable to any Qt version) and is `ON` by default.
But it is not a problem at all, not-existing options just trigger harmless warning.

**Comment by issakomi** [comment]
Another things I have mentioned in [build.log](https://kojipkgs.fedoraproject.org//work/tasks/4628/101904628/build.log)
There are attempts to set CMAKE_*_FLAGS_RELEASE flags, e.g. `-DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG`,
but the build type is set to _RelWithDebInfo_ `-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo`, so all RELEASE flags are not used, there are CMAKE_CXX_FLAGS_RELWITHDEBINFO for the build type _RelWithDebInfo_. **It is not a problem at all**, the flags are just trying to set `-DNDEBUG`, it is set in by AlizaMS cmake [here](https://kojipkgs.fedoraproject.org//work/tasks/4628/101904628/build.log) for all type except DEBUG of course, just FYI. Probably the flags set by Fedora's build system somehow automatically.
