### ISSUE TITLE
Ошибки сборки.

### ISSUE THREAD

**Issue by aaly11** [AlizaMedicalImaging/AlizaMS#28]
Привет. Создал несколько проектов на [Open Build Service](https://build.opensuse.org/) для сборки deb и rpm пакетов.
[Debian и Ubuntu Qt6](https://build.opensuse.org/package/show/home:AndnoVember:Debian/alizams)
[openSUSE Qt6](https://build.opensuse.org/package/show/home:AndnoVember:LXQt:Qt6/alizams)
[openSUSE Qt5](https://build.opensuse.org/package/show/home:AndnoVember:test/alizams)

В разное время, с разными настройками сборки, были следующие ошибки:

```
[  328s] /usr/src/packages/BUILD/mdcm/Source/Common/mdcmASN1.cxx: In static member function 'static bool mdcm::ASN1::ParseDump(const char*, size_t)':
[  328s] /usr/src/packages/BUILD/mdcm/Source/Common/mdcmASN1.cxx:70:3: error: 'assert' was not declared in this scope
[  328s]    70 |   assert(out);
[  328s]       |   ^~~~~~
[  328s] /usr/src/packages/BUILD/mdcm/Source/Common/mdcmASN1.cxx:35:1: note: 'assert' is defined in header '<cassert>'; did you forget to '#include <cassert>'?
[  328s]    34 | #include <fstream>
[  328s]   +++ |+#include <cassert>
[  328s]    35 | 
[  328s] make[3]: *** [CMakeFiles/alizams.dir/build.make:2657: CMakeFiles/alizams.dir/mdcm/Source/Common/mdcmASN1.cxx.o] Error 1
```

MDCM_USE_SYSTEM_OPENSSL:BOOL=**ON**
```
[  425s] /usr/src/packages/BUILD/mdcm/Source/Common/mdcmOpenSSLP7CryptographicMessageSyntax.cxx:488:72: error: virt-specifiers in 'SetPassword' not allowed outside a class definition
[  425s]   488 | OpenSSLP7CryptographicMessageSyntax::SetPassword(const char *, size_t) override
[  425s]       |                                                                        ^~~~~~~~
[  425s] make[3]: *** [CMakeFiles/alizams.dir/build.make:2741: CMakeFiles/alizams.dir/mdcm/Source/Common/mdcmOpenSSLP7CryptographicMessageSyntax.cxx.o] Error 1
```

**Comment by issakomi** [comment]
Thank you very much. I have [fixed](https://github.com/AlizaMedicalImaging/AlizaMS/commit/e0acb83725b3748cd46d393ccbaf214b1d2e744a) build issue with SSL enabled. Actually, SSL is not used, don't enable it, I have purposely hidden the option to enable SSL in MDCM.

Please kindly let me know if there will any issues.
Thank you!

**Comment by issakomi** [comment]
BTW, I have looked at packages. Thank you!

` unresolvable: nothing provides cmake(ITK) >= 5.3.0, (got version 4.13.2 provided by insighttoolkit-devel) `
ITK 4.13 is OK too.

**Comment by issakomi** [comment]
@aaly11 

> Actually, SSL is not used, don't enable it,

BTW, the same for PVRG `-DMDCM_USE_PVRG:BOOL=ON -DMDCM_USE_SYSTEM_PVRG:BOOL=ON`. It is [currently](https://github.com/AlizaMedicalImaging/AlizaMS/blob/4b4a1751b7998ba8e263e52a089a9a331d70b964/CMakeLists.txt#L133) not really good, maybe later. Default for _SSL_ and _PVRG_ is OFF, not necessary to set to OFF.

Thank you!

**Comment by aaly11** [comment]
> `unresolvable: nothing provides cmake(ITK) >= 5.3.0, (got version 4.13.2 provided by insighttoolkit-devel)` ITK 4.13 is OK too.

Сборка для openSUSE Leap 15.5 с Qt6 заканчивалась не удачей. ITK 4.13 не совместим с gcc 10. Компилятор задан макросом %cmake_qt6 (-DCMAKE_C_COMPILER:STRING=gcc-10 -DCMAKE_CXX_COMPILER:STRING=g++-10). Поэтому версию ITK повысил до 5.3.0, чтобы избежать не нужных и ресурсоёмких сборок.

**Comment by issakomi** [comment]
I have tried xUbuntu package (on Debian 12), works very good. Thank you!

BTW, the 1st _lintian_ error (s. below) can be silenced by creating the _alizams.lintian-overrides_ file with
`alizams: embedded-library usr/bin/alizams: libjpeg`
inside.
It is probably not required, just FYI. AlizaMS uses very special JPEG implementation, not compatible with usual JPEG, DICOM implements "lossless compression" (8, 12, 16 bits) and "lossy" (8, 12 bits), there are also several very special options implemented (to workaround some well-known bugs), so no chance for vanilla JPEG. Aliza's JPEG is mangled, sometimes the error appear, sometimes not, probably it depends on _lintian_ version.

```
r@deb2:~$ lintian Downloads/alizams_1.9.1+git1.e0acb83-1+7.1_amd64.deb 
E: alizams: embedded-library libjpeg [usr/bin/alizams]
E: alizams: malformed-deb-archive second (official) member control.tar.zst not control.tar.(gz|xz)
E: alizams: malformed-deb-archive third (official) member data.tar.zst not data.tar.(gz|xz|bz2|lzma)
```

So, in fact, there are no real errors, nice.

**Comment by issakomi** [comment]
I have added [Ubuntu 22.04](https://software.opensuse.org//download.html?project=home%3Aissakomi&package=alizams) for completeness, works with Qt5.
