### ISSUE TITLE
Builds/releases for win/mac went missing?

### ISSUE THREAD

**Issue by moeffju** [AlizaMedicalImaging/AlizaMS#33]
I had previously downloaded Aliza MS 1.8.3 built for Windows from this Github release page, but now I cannot find any releases for either Windows or macOS. Is that a deliberate decision, a mistake, or a Github bug? Are there build instructions for Win/Mac somewhere?

**Comment by issakomi** [comment]
Yes, you are right. Currently, there are only builds for free operating systems. I am not 100% sure about support for Windows and macOS releases yet.

**Comment by issakomi** [comment]
Nice that macOS build has worked. I am still not sure about macOS / Windows releases, sorry. Please give me some time. If you like, drop me an email to one of the addresses listed here https://www.aliza-dicom-viewer.com/info , I will send you a free license.
