### ISSUE TITLE
alizams ubuntu 22.04 illegal instruction error 

### ISSUE THREAD

**Issue by cappelikan** [AlizaMedicalImaging/AlizaMS#36]
I install from this 
https://software.opensuse.org//download.html?project=home%3Aissakomi%3AUbuntu-22.04&package=alizams

when starting the system i get error illegal instruction , I get an detalised error through the debugger

gdb alizams
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from alizams...
(No debugging symbols found in alizams)
(gdb) run
Starting program: /usr/bin/alizams 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00007ffff71230b0 in v3p_netlib_slamc2_ () from /lib/libitkv3p_netlib-5.2.so.1

My system 

Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.2.0-1012-lowlatency (64-bit)
Graphics Platform: X11
Processors: 2 × Intel® Core™2 Duo CPU E4700 @ 2.60GHz
Memory: 2.8 ГіБ of RAM
Graphics Processor: GeForce 210/PCIe/SSE2
Product Name: 775i945GZ

**Comment by issakomi** [comment]
> Processors: 2 × Intel® Core™2 Duo CPU E4700 @ 2.60GHz

> 
> Program received signal SIGILL, Illegal instruction.
> 0x00007ffff71230b0 in v3p_netlib_slamc2_ () from /lib/libitkv3p_netlib-5.2.so.1

It seems that there is some instruction that the CPU doesn't support. In the ITK-5.2 library. A wild guess that is could be some AVX instruction (since 2011, CPU is 2008). If I remember correctly there were changes in the related stuff in the ITK.

Does the [single binary](https://github.com/AlizaMedicalImaging/AlizaMS/releases/download/v1.9.3/alizams_binary_only-1.9.3.tar.gz) (from 1.9.3 release) works?

**Comment by cappelikan** [comment]
> > Processors: 2 × Intel® Core™2 Duo CPU E4700 @ 2.60GHz
> 
> > Program received signal SIGILL, Illegal instruction.
> > 0x00007ffff71230b0 in v3p_netlib_slamc2_ () from /lib/libitkv3p_netlib-5.2.so.1
> 
> It seems that there is some instruction that the CPU doesn't support. In the ITK-5.2 library. A wild guess that is could be some AVX instruction (since 2011, CPU is 2008). If I remember correctly there were changes in the related stuff in the ITK.
> 
> Does the [single binary](https://github.com/AlizaMedicalImaging/AlizaMS/releases/download/v1.9.3/alizams_binary_only-1.9.3.tar.gz) (from 1.9.3 release) works?

Yes single binary it`s worked
