### ISSUE TITLE
What about Flatpak

### ISSUE THREAD

**Issue by alcir** [AlizaMedicalImaging/AlizaMS#5]
I was playing with Flatpak.
What do you think to publish AlizaMS on Flathub?
It doesn't seem too complicated at a first glance.
https://github.com/alcir/flathub/tree/com.alizadicomviewer.AlizaMS

**Comment by issakomi** [comment]
Thank you. Of course, if you like feel free to add to Flatpak. I dind't know about it before. IMHO, the original Fedora package in is cooler, thank you the the package! This Flatpak will can trigger additional work with maintaining. There are relatively many downloads already, the last version published here at 3 Oct has [10-20 downloads per day](https://somsubhra.github.io/github-release-stats/?username=AlizaMedicalImaging&repository=AlizaMS&page=1&per_page=1), i have mentioned Fedora package in [Release info](https://github.com/AlizaMedicalImaging/AlizaMS/releases/tag/v1.7.0), maybe some users prefer Fedora package.

P.S. By chance I discovered that there is also Arch Linux  [package](https://aur.archlinux.org/packages/alizams/).

**Comment by issakomi** [comment]
https://github.com/flathub/flathub/pull/2679/files#r767896203

> I will try. It requires some dependencies (ITK, that in turn requires gdcm, swig, eigen3, etc.)

BTW, ITK contains everything, it is usually Linux distribution's policy to use system libraries instead. It is possible to [build](https://github.com/AlizaMedicalImaging/AlizaMS/wiki) only with ITK and Qt. Import is to disable testing in ITK (enabled by default), it will take long and many GBs disk space. Without testing it is very fast. Just FYI.

**Comment by alcir** [comment]
What do you think about the app-id?
com.alizadicomviewer.AlizaMS is ok
or com.github.AlizaMedicalImaging.AlizaMS would be better?

ref. https://docs.flatpak.org/en/latest/conventions.html#application-ids

**Comment by issakomi** [comment]
I use for macOS this one, but as you like
`    MACOSX_BUNDLE_GUI_IDENTIFIER "com.aliza.alizams"`

**Comment by alcir** [comment]
As you see, if I'm not wrong, flatpak guidelines suggest to use a reverse FQDN that actually exist.

**Comment by issakomi** [comment]
Oh, sorry, got it now. Probably _github_ is better, but as you like.

**Comment by issakomi** [comment]
I have looked at the the discussion https://github.com/flathub/flathub/pull/2679
Some notes about build, if the policy allows better just build ITK with default configuration only without testing, maybe use _"release with debug info"_ too, if it this type is used for AlizaMS. Default build will _statically_ link everything, only _alizams_ binary will exist. AlizaMS uses a very small part of ITK, no Python, no other wrapping (swig), no GDCM. Just required parts of core ITK will be linked, that all.

**Comment by alcir** [comment]
Yep. But as far as I understand, in order to build ITK, I need swig, gdcm, etc. 
If I'm not wrong, I try to build ITK only, and it was complaining about such dependencies.
BTW I will try again.

**Comment by issakomi** [comment]
With default _cmake_ option no dependencies, like here
https://github.com/AlizaMedicalImaging/AlizaMS/wiki#itk

**Comment by issakomi** [comment]
Maybe there are some system things overriding something... like Fedora _cmake_ macro forced shared libs.

**Comment by alcir** [comment]
It works only with ITK.
Probably the clue was that I was specifying `-DITK_USE_SYSTEM_GDCM:BOOL=ON` and so on.
Let's see what the reviewer thinks.

**Comment by alcir** [comment]
https://github.com/flathub/flathub/pull/2679#issuecomment-999378495

**Comment by alcir** [comment]
Here we are
https://flathub.org/apps/details/com.github.AlizaMedicalImaging.AlizaMS
🎉

**Comment by issakomi** [comment]
Thank you very much. I have seen the Flatpak update. I was a little bit too late with 1.7.4, sorry. I hope this release will be actual for many month (unless something important appears).
Merry Christmas and a happy New Year!

**Comment by alcir** [comment]
No problem at all.
Tahnk you for your great work.
