### ISSUE TITLE
Support for brew on MacOS

### ISSUE THREAD

**Issue by evulhotdog** [AlizaMedicalImaging/AlizaMS#9]
Are you planning on supporting Homebrew on MacOS for downloading the application?

**Comment by issakomi** [comment]
Honestly, i don't have plans for Homebrew now.

**Comment by issakomi** [comment]
It is easy to compile on macOS, specially native, s.
https://github.com/AlizaMedicalImaging/AlizaMS/wiki/Example-build-on-macOS
To build a release with universal binary is a little bit more tricky.
